export const DEFAULT_EVENTS = [
  // Pre-wedding
  { id:1,  name:"Roka",          emoji:"🪔", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:0  },
  { id:2,  name:"Sagai",         emoji:"💍", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:1  },
  { id:3,  name:"Ganesh Puja",   emoji:"🐘", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:2  },
  { id:4,  name:"Haldi",         emoji:"🌿", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:3  },
  { id:5,  name:"Mehndi",        emoji:"🌸", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:4  },
  { id:6,  name:"Sangeet",       emoji:"🎶", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:5  },
  // Wedding day
  { id:7,  name:"Baraat",        emoji:"🐴", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:6  },
  { id:8,  name:"Jaimala",       emoji:"🌹", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:7  },
  { id:9,  name:"Pheras",        emoji:"🔥", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:8  },
  { id:10, name:"Kanyadaan",     emoji:"🙏", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:9  },
  { id:11, name:"Saptapadi",     emoji:"🪷", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:10 },
  { id:12, name:"Sindoor Daan",  emoji:"❤️", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:11 },
  // Post-wedding
  { id:13, name:"Reception",     emoji:"👑", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:12 },
  { id:14, name:"Vidaai",        emoji:"💐", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:13 },
  { id:15, name:"Griha Pravesh", emoji:"🏠", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:14 },
];

export const BUDGET_CATEGORIES = [
  { id:"venue", label:"Venue", emoji:"🏛️", color:"#E53935" },
  { id:"catering", label:"Catering", emoji:"🍽️", color:"#F57C00" },
  { id:"decor", label:"Decor & Flowers", emoji:"🌺", color:"#7B1FA2" },
  { id:"photography", label:"Photography & Video", emoji:"📸", color:"#1565C0" },
  { id:"attire", label:"Attire & Jewelry", emoji:"💍", color:"#C62828" },
  { id:"beauty", label:"Beauty & Grooming", emoji:"💄", color:"#8E24AA" },
  { id:"music", label:"Music & DJ", emoji:"🎵", color:"#00796B" },
  { id:"invites", label:"Invitations", emoji:"💌", color:"#AD1457" },
  { id:"transport", label:"Transport", emoji:"🚌", color:"#4527A0" },
  { id:"stay", label:"Stay & Travel", emoji:"🏨", color:"#00838F" },
  { id:"pandit", label:"Pandit & Rituals", emoji:"🪔", color:"#E65100" },
  { id:"vendors", label:"Vendor Payments", emoji:"🤝", color:"#6D4C41" },
  { id:"misc", label:"Miscellaneous", emoji:"✨", color:"#37474F" },
];

export const EXPENSE_AREAS = [
  { id:"ceremony", label:"Ceremony", emoji:"🪔" },
  { id:"guests", label:"Guests", emoji:"👥" },
  { id:"bride", label:"Bride", emoji:"👰" },
  { id:"groom", label:"Groom", emoji:"🤵" },
  { id:"vendors", label:"Vendors", emoji:"🤝" },
  { id:"general", label:"General", emoji:"✨" },
];

const DEFAULT_VENDOR_CATALOG = [
  {
    type: "Venue",
    emoji: "🏛️",
    city: "Delhi",
    rating: 5,
    priceLevel: 4,
    guestRange: { min: 250, max: 1200 },
    budgetRange: { min: 600000, max: 2200000 },
    pricePerPlate: 3200,
    typicalTiming: "8-10 hrs booking slot",
    serviceMode: "Banquet and lawn venue",
    services: ["Grand ballroom setup", "Poolside phera zone", "Luxury bridal suite", "In-house valet", "Venue walk-through planning"],
    locations: ["Delhi", "Gurgaon", "Noida"],
    testimonials: [
      { author: "Rhea & Kunal", text: "The venue team handled guest flow and decor timing beautifully." },
      { author: "Aastha Family", text: "Food stations, parking, and bridal room support felt premium throughout." },
    ],
    reviewPrompt: "Share your experience with the venue, team coordination, and guest comfort.",
    address: "NH8 Wedding Mile, Delhi NCR",
    mapQuery: "Luxury wedding venue NH8 Delhi NCR",
  },
  {
    type: "Photography",
    emoji: "📸",
    city: "Gurgaon",
    rating: 5,
    priceLevel: 3,
    budgetRange: { min: 180000, max: 450000 },
    typicalTiming: "10-12 hrs coverage",
    serviceMode: "Photo and film team",
    services: ["Candid photography", "Wedding film", "Pre-wedding concept shoot", "Drone coverage", "Same-day teaser edits"],
    locations: ["Gurgaon", "Delhi", "Jaipur"],
    testimonials: [
      { author: "Mitali", text: "Their candid moments felt natural and the teaser arrived in two days." },
      { author: "Harsh", text: "Strong crowd management and very clean family portrait coordination." },
    ],
    reviewPrompt: "Tell couples how the team handled coverage, delivery speed, and overall vibe.",
  },
  {
    type: "Catering",
    emoji: "🍽️",
    city: "Delhi",
    rating: 5,
    priceLevel: 4,
    guestRange: { min: 150, max: 1500 },
    budgetRange: { min: 250000, max: 1800000 },
    pricePerPlate: 2400,
    typicalTiming: "4-8 hrs live service",
    serviceMode: "Multi-cuisine catering",
    services: ["Regional menus", "Live counters", "Mocktail islands", "Dessert room", "Tasting session before booking"],
    locations: ["Delhi", "Faridabad", "Noida"],
    testimonials: [
      { author: "Shivangi", text: "The chaat counter and desserts were the most talked-about part of the wedding." },
      { author: "Malhotra Family", text: "Excellent service pace even with a packed baraat arrival." },
    ],
    reviewPrompt: "Review the menu, service pace, food quality, and presentation.",
  },
  {
    type: "Bartender",
    emoji: "🍸",
    city: "Gurgaon",
    rating: 4,
    priceLevel: 3,
    budgetRange: { min: 50000, max: 180000 },
    pricePerPlate: 850,
    typicalTiming: "5-6 hrs bar service",
    serviceMode: "Signature bar service",
    services: ["Cocktail curation", "Flair bartending", "His and hers signature drinks", "Glassware management", "Dry-day compliant planning"],
    locations: ["Gurgaon", "Delhi", "Manesar"],
    testimonials: [
      { author: "Ankit", text: "The custom cocktail menu made our sangeet feel genuinely personal." },
    ],
    reviewPrompt: "How was the bar setup, menu, staff professionalism, and pacing?",
  },
  {
    type: "Decoration",
    emoji: "🌺",
    city: "Delhi",
    rating: 5,
    priceLevel: 4,
    budgetRange: { min: 220000, max: 1200000 },
    typicalTiming: "10-14 hrs setup",
    serviceMode: "Floral and production decor",
    services: ["Mandap styling", "Entry tunnels", "Fresh floral ceiling", "Stage production", "Custom mood-board execution"],
    locations: ["Delhi", "Noida", "Jaipur"],
    testimonials: [
      { author: "Naina", text: "The stage looked even better than the reference board we shared." },
    ],
    reviewPrompt: "Review the decor execution, floral freshness, and responsiveness to changes.",
  },
  {
    type: "Makeup Artist",
    emoji: "💄",
    city: "Delhi",
    rating: 5,
    priceLevel: 3,
    budgetRange: { min: 35000, max: 125000 },
    typicalTiming: "3-5 hrs glam session",
    serviceMode: "Bride and family glam",
    services: ["Bridal makeup", "Hair styling", "Draping support", "Family packages", "Touch-up stay-on service"],
    locations: ["Delhi", "Noida", "Gurgaon"],
    testimonials: [
      { author: "Ira", text: "The makeup held through pheras and reception without feeling heavy." },
    ],
    reviewPrompt: "Describe the makeup finish, punctuality, and how the look photographed.",
  },
  {
    type: "Jewellery",
    emoji: "💍",
    city: "Delhi",
    rating: 4,
    priceLevel: 4,
    budgetRange: { min: 75000, max: 600000 },
    typicalTiming: "By appointment",
    serviceMode: "Custom bridal jewellery",
    services: ["Polki sets", "Temple jewellery", "Bridesmaid styling", "Customization consults", "Trial styling appointments"],
    locations: ["Delhi", "Chandni Chowk", "Karol Bagh"],
    testimonials: [
      { author: "Pallavi", text: "They helped balance statement pieces without overloading the bridal look." },
    ],
    reviewPrompt: "How was the collection quality, styling guidance, and after-sales support?",
  },
  {
    type: "Rent & Buy",
    emoji: "🛍️",
    city: "Noida",
    rating: 4,
    priceLevel: 2,
    budgetRange: { min: 10000, max: 180000 },
    typicalTiming: "Flexible pickup and return",
    serviceMode: "Rental and purchase options",
    services: ["Lehenga rentals", "Sherwani rentals", "Accessory purchase", "Styling consultations", "Last-minute alteration support"],
    locations: ["Noida", "Delhi", "Gurgaon"],
    testimonials: [
      { author: "Ritu", text: "Perfect for secondary functions when buying every outfit just did not make sense." },
    ],
    reviewPrompt: "Share whether the rental quality, fit, and exchange process worked well.",
  },
  {
    type: "Mehndi",
    emoji: "🌿",
    city: "Delhi",
    rating: 5,
    priceLevel: 2,
    budgetRange: { min: 15000, max: 70000 },
    typicalTiming: "4-8 hrs application",
    serviceMode: "Bridal and guest mehndi",
    services: ["Bridal intricate mehndi", "Guest artist pool", "Arabic and traditional styles", "Express guest queue", "Aftercare guidance"],
    locations: ["Delhi", "Noida", "Faridabad"],
    testimonials: [
      { author: "Sanya", text: "Dark stain, clean detailing, and the guest artists were very efficient." },
    ],
    reviewPrompt: "Review stain quality, detail work, guest handling, and artist punctuality.",
  },
  {
    type: "Wedding Cards",
    emoji: "💌",
    city: "Delhi",
    rating: 4,
    priceLevel: 2,
    budgetRange: { min: 12000, max: 150000 },
    typicalTiming: "7-14 days production",
    serviceMode: "Print and digital invites",
    services: ["Luxury box invites", "Minimal card suites", "Digital e-invites", "Wax seal finishing", "Multilingual content support"],
    locations: ["Delhi", "Mumbai", "Online nationwide"],
    testimonials: [
      { author: "Vidhi", text: "They turned our family notes into a polished card set very quickly." },
    ],
    reviewPrompt: "How was the design process, printing quality, and timeline reliability?",
  },
  {
    type: "Choreographer",
    emoji: "💃",
    city: "Gurgaon",
    rating: 5,
    priceLevel: 3,
    budgetRange: { min: 30000, max: 175000 },
    typicalTiming: "6-10 practice sessions",
    serviceMode: "Family dance direction",
    services: ["Sangeet concept planning", "Couple performance mix", "Family medleys", "At-home rehearsals", "Stage blocking support"],
    locations: ["Gurgaon", "Delhi", "Noida"],
    testimonials: [
      { author: "Kartik", text: "They made non-dancers feel comfortable and still delivered a sharp performance." },
    ],
    reviewPrompt: "Tell others how the sessions felt and whether the routines were wedding-friendly.",
  },
  {
    type: "Music",
    emoji: "🎵",
    city: "Noida",
    rating: 4,
    priceLevel: 2,
    budgetRange: { min: 40000, max: 160000 },
    typicalTiming: "4-5 hrs performance",
    serviceMode: "DJ and sound",
    services: ["Wedding DJ", "Sound console", "Live dhol sync", "Cold pyros coordination", "After-party set"],
    locations: ["Noida", "Delhi", "Ghaziabad"],
    testimonials: [
      { author: "Surbhi", text: "Great read on the room, especially during baraat and late-night dance sets." },
    ],
    reviewPrompt: "Review music selection, sound quality, and crowd energy management.",
  },
  {
    type: "Pandit",
    emoji: "🪔",
    city: "Delhi",
    rating: 5,
    priceLevel: 1,
    budgetRange: { min: 11000, max: 51000 },
    typicalTiming: "2-4 hrs rituals",
    serviceMode: "Wedding rituals and guidance",
    services: ["Phera rituals", "Muhurat planning", "Sankalp guidance", "Bilingual explanations", "Samagri checklist"],
    locations: ["Delhi", "Gurgaon", "Noida"],
    testimonials: [
      { author: "The Bhatias", text: "Calm, punctual, and explained each step clearly for both families." },
    ],
    reviewPrompt: "Share how clearly the rituals were explained and how smoothly the ceremony ran.",
  },
];

export const DEFAULT_VENDORS = DEFAULT_VENDOR_CATALOG.map((vendor, index) => ({
  id: index + 1,
  name: `VivahGo's Choice ${vendor.type}`,
  booked: vendor.type === "Venue" || vendor.type === "Pandit",
  featured: true,
  featuredLabel: "VivahGo's Choice",
  reviewCount: vendor.testimonials.length + (vendor.rating >= 5 ? 18 : 11),
  ...vendor,
}));

export const DEFAULT_TASKS = [
  { id:1, name:"Finalize overall wedding calendar", done:true, due:"6 months before", priority:"high", group:"6 months", eventId:"", ceremony:"General" },
  { id:2, name:"Book main wedding venue", done:true, due:"6 months before", priority:"high", group:"6 months", eventId:9, ceremony:"Pheras" },
  { id:3, name:"Block guest room inventory", done:false, due:"5 months before", priority:"high", group:"5 months", eventId:"", ceremony:"General" },
  { id:4, name:"Freeze photography and video team", done:false, due:"5 months before", priority:"high", group:"5 months", eventId:"", ceremony:"General" },
  { id:5, name:"Finalize Roka guest flow", done:false, due:"4 months before", priority:"medium", group:"4 months", eventId:1, ceremony:"Roka" },
  { id:6, name:"Arrange Sagai ring and stage design", done:false, due:"4 months before", priority:"medium", group:"4 months", eventId:2, ceremony:"Sagai" },
  { id:7, name:"Book haldi floral decor", done:false, due:"3 months before", priority:"high", group:"3 months", eventId:4, ceremony:"Haldi" },
  { id:8, name:"Finalize mehndi artists", done:false, due:"3 months before", priority:"high", group:"3 months", eventId:5, ceremony:"Mehndi" },
  { id:9, name:"Freeze Sangeet choreography slots", done:false, due:"3 months before", priority:"medium", group:"3 months", eventId:6, ceremony:"Sangeet" },
  { id:10, name:"Send invitation cards and e-invites", done:false, due:"2 months before", priority:"high", group:"2 months", eventId:"", ceremony:"General" },
  { id:11, name:"Assign family welcome teams", done:false, due:"2 months before", priority:"medium", group:"2 months", eventId:"", ceremony:"General" },
  { id:12, name:"Finalize baraat transport logistics", done:false, due:"1 month before", priority:"high", group:"1 month", eventId:7, ceremony:"Baraat" },
  { id:13, name:"Confirm jaimala setup and sequence", done:false, due:"1 month before", priority:"medium", group:"1 month", eventId:8, ceremony:"Jaimala" },
  { id:14, name:"Confirm pandit and phera muhurat", done:false, due:"1 month before", priority:"high", group:"1 month", eventId:9, ceremony:"Pheras" },
  { id:15, name:"Prepare kanyadaan rituals checklist", done:false, due:"3 weeks before", priority:"medium", group:"Final", eventId:10, ceremony:"Kanyadaan" },
  { id:16, name:"Finalize saptapadi vow prompts", done:false, due:"3 weeks before", priority:"medium", group:"Final", eventId:11, ceremony:"Saptapadi" },
  { id:17, name:"Arrange sindoor daan items", done:false, due:"2 weeks before", priority:"high", group:"Final", eventId:12, ceremony:"Sindoor Daan" },
  { id:18, name:"Confirm reception stage and MC plan", done:false, due:"2 weeks before", priority:"high", group:"Final", eventId:13, ceremony:"Reception" },
  { id:19, name:"Finalize vidaai vehicle and timing", done:false, due:"1 week before", priority:"high", group:"Final", eventId:14, ceremony:"Vidaai" },
  { id:20, name:"Prepare griha pravesh welcome setup", done:false, due:"1 week before", priority:"medium", group:"Final", eventId:15, ceremony:"Griha Pravesh" },
  { id:21, name:"Print emergency vendor contact sheet", done:false, due:"5 days before", priority:"high", group:"Final", eventId:"", ceremony:"General" },
  { id:22, name:"Pack jewelry and attire day-wise", done:false, due:"4 days before", priority:"high", group:"Final", eventId:"", ceremony:"General" },
  { id:23, name:"Share final timeline with core family", done:false, due:"3 days before", priority:"high", group:"Final", eventId:"", ceremony:"General" },
  { id:24, name:"Settle pending vendor balances", done:false, due:"2 days before", priority:"high", group:"Final", eventId:"", ceremony:"General" },
  { id:25, name:"Create post-event photo backup plan", done:false, due:"After wedding", priority:"low", group:"Post Wedding", eventId:"", ceremony:"General" },
];

export const QUESTIONS = [
  { key:"bride", q:"What is the bride's name? 🌸", placeholder:"Enter bride's name...", type:"text" },
  { key:"groom", q:"And the groom's name? 🤵", placeholder:"Enter groom's name...", type:"text" },
  { key:"date", q:"What's your dream wedding date? 📅", placeholder:"e.g. 25 November 2025", type:"text" },
  { key:"venue", q:"Which city or venue are you considering? 🏛️", placeholder:"e.g. Delhi, Jaipur, Udaipur...", type:"text" },
  { key:"guests", q:"How many guests are you expecting? 👨‍👩‍👧‍👦", placeholder:"e.g. 300", type:"text" },
  { key:"budget", q:"What's your total wedding budget (₹)? 💰", placeholder:"e.g. 50,00,000", type:"text" },
];

export const AI_RESPONSES = [
  "Wonderful! ",
  "Lovely name! ",
  "Exciting! ",
  "Great choice! ",
  "Perfect! ",
  "Excellent! ",
];
