export const DEFAULT_EVENTS = [
  // Pre-wedding
  { id:1,  name:"Roka",          emoji:"🪔", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:0  },
  { id:2,  name:"Sagai",         emoji:"💍", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:1  },
  { id:3,  name:"Ganesh Puja",   emoji:"🐘", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:2  },
  { id:4,  name:"Haldi",         emoji:"🌿", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:3  },
  { id:5,  name:"Mehndi",        emoji:"🌸", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:4  },
  { id:6,  name:"Sangeet",       emoji:"🎶", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:5  },
  // Wedding day
  { id:7,  name:"Baraat",        emoji:"🐴", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:6  },
  { id:8,  name:"Jaimala",       emoji:"🌹", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:7  },
  { id:9,  name:"Pheras",        emoji:"🔥", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:8  },
  { id:10, name:"Kanyadaan",     emoji:"🙏", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:9  },
  { id:11, name:"Saptapadi",     emoji:"🪷", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:10 },
  { id:12, name:"Sindoor Daan",  emoji:"❤️", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:11 },
  // Post-wedding
  { id:13, name:"Reception",     emoji:"👑", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:12 },
  { id:14, name:"Vidaai",        emoji:"💐", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:13 },
  { id:15, name:"Griha Pravesh", emoji:"🏠", date:"", time:"", venue:"", status:"upcoming", note:"", colorIdx:14 },
];

export const BUDGET_CATEGORIES = [
  { id:"venue", label:"Venue", emoji:"🏛️", color:"#E53935" },
  { id:"catering", label:"Catering", emoji:"🍽️", color:"#F57C00" },
  { id:"decor", label:"Decor & Flowers", emoji:"🌺", color:"#7B1FA2" },
  { id:"photography", label:"Photography & Video", emoji:"📸", color:"#1565C0" },
  { id:"attire", label:"Attire & Jewelry", emoji:"💍", color:"#C62828" },
  { id:"beauty", label:"Beauty & Grooming", emoji:"💄", color:"#8E24AA" },
  { id:"music", label:"Music & DJ", emoji:"🎵", color:"#00796B" },
  { id:"invites", label:"Invitations", emoji:"💌", color:"#AD1457" },
  { id:"transport", label:"Transport", emoji:"🚌", color:"#4527A0" },
  { id:"stay", label:"Stay & Travel", emoji:"🏨", color:"#00838F" },
  { id:"pandit", label:"Pandit & Rituals", emoji:"🪔", color:"#E65100" },
  { id:"vendors", label:"Vendor Payments", emoji:"🤝", color:"#6D4C41" },
  { id:"misc", label:"Miscellaneous", emoji:"✨", color:"#37474F" },
];

export const EXPENSE_AREAS = [
  { id:"ceremony", label:"Ceremony", emoji:"🪔" },
  { id:"guests", label:"Guests", emoji:"👥" },
  { id:"bride", label:"Bride", emoji:"👰" },
  { id:"groom", label:"Groom", emoji:"🤵" },
  { id:"vendors", label:"Vendors", emoji:"🤝" },
  { id:"general", label:"General", emoji:"✨" },
];

const DEFAULT_VENDOR_CATALOG = [
  {
    type: "Venue",
    subType: "Wedding Resorts",
    bundledServices: ["Catering", "Wedding Transportation", "Wedding Decorators"],
    emoji: "🏛️",
    city: "Delhi",
    rating: 5,
    priceLevel: 4,
    guestRange: { min: 250, max: 1200 },
    budgetRange: { min: 600000, max: 2200000 },
    pricePerPlate: 3200,
    typicalTiming: "8-10 hrs booking slot",
    serviceMode: "Resort and destination venue",
    services: ["Wedding resort booking", "Bridal suite", "Guest room blocks", "Outdoor phera lawns", "Venue recce planning"],
    locations: ["Delhi", "Gurgaon", "Jaipur"],
    testimonials: [
      { author: "Rhea & Kunal", text: "The venue team handled guest flow and decor timing beautifully." },
      { author: "Aastha Family", text: "Parking, rooms, and hospitality felt premium end to end." },
    ],
    reviewPrompt: "Share your experience with the venue, team coordination, and guest comfort.",
    address: "NH8 Wedding Mile, Delhi NCR",
    mapQuery: "Luxury wedding resort NH8 Delhi NCR",
  },
  {
    type: "Catering",
    emoji: "🍽️",
    city: "Delhi",
    rating: 5,
    priceLevel: 4,
    guestRange: { min: 150, max: 1500 },
    budgetRange: { min: 250000, max: 1800000 },
    pricePerPlate: 2400,
    typicalTiming: "4-8 hrs live service",
    serviceMode: "North Indian and regional catering",
    services: ["Regional menus", "Live counters", "Dessert room", "Cocktail snacks", "Tasting session before booking"],
    locations: ["Delhi", "Noida", "Faridabad"],
    testimonials: [
      { author: "Shivangi", text: "The chaat counter and desserts were the most talked-about part of the wedding." },
    ],
    reviewPrompt: "Review the menu, service pace, food quality, and presentation.",
  },
  {
    type: "Wedding Invitations",
    subType: "Luxury Box Invitations",
    emoji: "💌",
    city: "Delhi",
    rating: 4,
    priceLevel: 2,
    budgetRange: { min: 12000, max: 150000 },
    typicalTiming: "7-14 days production",
    serviceMode: "Print and digital invites",
    services: ["Luxury box invites", "Minimal card suites", "Digital e-invites", "Wax seal finishing", "Multilingual copy support"],
    locations: ["Delhi", "Mumbai", "Online nationwide"],
    testimonials: [
      { author: "Vidhi", text: "They turned our family notes into a polished card set very quickly." },
    ],
    reviewPrompt: "How was the design process, printing quality, and timeline reliability?",
  },
  {
    type: "Wedding Gifts",
    subType: "Guest Hampers",
    emoji: "🎁",
    city: "Jaipur",
    rating: 4,
    priceLevel: 2,
    budgetRange: { min: 10000, max: 220000 },
    typicalTiming: "5-12 days fulfillment",
    serviceMode: "Hampers and guest gifting",
    services: ["Welcome hampers", "Shagun trays", "Bridesmaid gifts", "Custom gifting tags", "Bulk packaging"],
    locations: ["Jaipur", "Delhi", "Online nationwide"],
    testimonials: [
      { author: "Mona", text: "The hampers looked elevated and still stayed within budget." },
    ],
    reviewPrompt: "How was the gifting quality, packaging, and delivery experience?",
  },
  {
    type: "Photography",
    emoji: "📸",
    city: "Gurgaon",
    rating: 5,
    priceLevel: 3,
    budgetRange: { min: 180000, max: 450000 },
    typicalTiming: "10-12 hrs coverage",
    serviceMode: "Photo storytelling team",
    services: ["Candid photography", "Family portraits", "Pre-wedding concept shoot", "Drone coverage", "Same-day teaser edits"],
    locations: ["Gurgaon", "Delhi", "Jaipur"],
    testimonials: [
      { author: "Mitali", text: "Their candid moments felt natural and the teaser arrived in two days." },
    ],
    reviewPrompt: "Tell couples how the team handled coverage, delivery speed, and overall vibe.",
  },
  {
    type: "Music",
    subType: "Live Band",
    emoji: "🎵",
    city: "Noida",
    rating: 4,
    priceLevel: 2,
    budgetRange: { min: 40000, max: 160000 },
    typicalTiming: "4-5 hrs performance",
    serviceMode: "Live band and sound support",
    services: ["Sufi band", "Instrumental entry", "Sound console", "Baraat sync", "Late-night set support"],
    locations: ["Noida", "Delhi", "Ghaziabad"],
    testimonials: [
      { author: "Surbhi", text: "Great read on the room, especially during baraat and late-night dance sets." },
    ],
    reviewPrompt: "Review music selection, sound quality, and crowd energy management.",
  },
  {
    type: "Wedding Transportation",
    subType: "Guest Transport",
    emoji: "🚌",
    city: "Delhi",
    rating: 4,
    priceLevel: 2,
    budgetRange: { min: 25000, max: 220000 },
    typicalTiming: "Full-day transport blocks",
    serviceMode: "Guest and family transportation",
    services: ["Airport pickups", "Guest coaches", "Shuttle loops", "VIP car allocation", "Driver coordination"],
    locations: ["Delhi", "Gurgaon", "Noida"],
    testimonials: [
      { author: "Bhatia Family", text: "The shuttle planning made guest logistics much easier than expected." },
    ],
    reviewPrompt: "How was the punctuality, fleet quality, and guest coordination?",
  },
  {
    type: "Tent House",
    emoji: "⛺",
    city: "Jaipur",
    rating: 4,
    priceLevel: 3,
    budgetRange: { min: 80000, max: 450000 },
    typicalTiming: "1-2 day setup",
    serviceMode: "Tent and outdoor infrastructure",
    services: ["Canopy structures", "Lounge seating", "Weather covers", "Dining tents", "Generator support"],
    locations: ["Jaipur", "Delhi", "Udaipur"],
    testimonials: [
      { author: "Raghav", text: "They handled an outdoor setup with backup planning very confidently." },
    ],
    reviewPrompt: "Review the tent quality, weather readiness, and production execution.",
  },
  {
    type: "Wedding Entertainment",
    subType: "Live Performers",
    emoji: "🎭",
    city: "Mumbai",
    rating: 4,
    priceLevel: 3,
    budgetRange: { min: 40000, max: 300000 },
    typicalTiming: "Per function booking",
    serviceMode: "Acts and crowd entertainment",
    services: ["Live acts", "LED performers", "Anchor support", "Baraat entertainers", "Kids activity corners"],
    locations: ["Mumbai", "Delhi", "Jaipur"],
    testimonials: [
      { author: "Pooja", text: "The entertainers kept the sangeet energy high without feeling tacky." },
    ],
    reviewPrompt: "Tell others how the act quality and audience engagement felt live.",
  },
  {
    type: "Florists",
    subType: "Fresh Venue Florals",
    emoji: "🌷",
    city: "Delhi",
    rating: 5,
    priceLevel: 3,
    budgetRange: { min: 50000, max: 300000 },
    typicalTiming: "Fresh floral setup",
    serviceMode: "Fresh floral styling",
    services: ["Varmala flowers", "Fresh stage florals", "Entry blooms", "Table flowers", "Car floral decor"],
    locations: ["Delhi", "Noida", "Jaipur"],
    testimonials: [
      { author: "Niharika", text: "The flowers stayed fresh through the evening and photographed beautifully." },
    ],
    reviewPrompt: "How were the floral quality, freshness, and execution?",
  },
  {
    type: "Wedding Planners",
    subType: "Full Planning",
    bundledServices: ["Wedding Decorators", "Wedding Entertainment", "Wedding Transportation"],
    emoji: "🗂️",
    city: "Delhi",
    rating: 5,
    priceLevel: 4,
    budgetRange: { min: 150000, max: 900000 },
    typicalTiming: "Full planning cycle",
    serviceMode: "End-to-end wedding planning",
    services: ["Budget planning", "Vendor coordination", "Family logistics", "Show calling", "Function timelines"],
    locations: ["Delhi", "Jaipur", "Goa"],
    testimonials: [
      { author: "Devika", text: "They kept every family member aligned and reduced a lot of stress." },
    ],
    reviewPrompt: "Review the planning quality, responsiveness, and on-ground execution.",
  },
  {
    type: "Wedding Videography",
    subType: "Cinematic Wedding Films",
    emoji: "🎥",
    city: "Gurgaon",
    rating: 5,
    priceLevel: 3,
    budgetRange: { min: 125000, max: 350000 },
    typicalTiming: "Multi-day coverage",
    serviceMode: "Cinematic wedding films",
    services: ["Highlight films", "Instagram reels", "Full ceremony film", "Drone footage", "Family interviews"],
    locations: ["Gurgaon", "Delhi", "Jaipur"],
    testimonials: [
      { author: "Kavya", text: "The final wedding film felt cinematic without missing family moments." },
    ],
    reviewPrompt: "How did the final film feel in terms of storytelling and delivery?",
  },
  {
    type: "Honeymoon",
    emoji: "✈️",
    city: "Delhi",
    rating: 4,
    priceLevel: 3,
    budgetRange: { min: 80000, max: 450000 },
    typicalTiming: "Trip planning support",
    serviceMode: "Post-wedding travel planning",
    services: ["Visa support", "Luxury itineraries", "Mini-moon ideas", "Flight and hotel booking", "Experience curation"],
    locations: ["Delhi", "Mumbai", "Online nationwide"],
    testimonials: [
      { author: "Aditi", text: "They handled travel planning while we were still in the wedding rush." },
    ],
    reviewPrompt: "Review the trip planning, personalization, and booking ease.",
  },
  {
    type: "Wedding Decorators",
    subType: "Mandap Decor",
    bundledServices: ["Florists", "Tent House"],
    emoji: "🌺",
    city: "Delhi",
    rating: 5,
    priceLevel: 4,
    budgetRange: { min: 220000, max: 1200000 },
    typicalTiming: "10-14 hrs setup",
    serviceMode: "Wedding decor production",
    services: ["Mandap styling", "Entry tunnels", "Fresh floral ceiling", "Stage production", "Mood-board execution"],
    locations: ["Delhi", "Noida", "Jaipur"],
    testimonials: [
      { author: "Naina", text: "The stage looked even better than the reference board we shared." },
    ],
    reviewPrompt: "Review the decor execution, floral freshness, and responsiveness to changes.",
  },
  {
    type: "Wedding Cakes",
    subType: "Tiered Wedding Cakes",
    emoji: "🎂",
    city: "Delhi",
    rating: 4,
    priceLevel: 2,
    budgetRange: { min: 12000, max: 85000 },
    typicalTiming: "Made to order",
    serviceMode: "Wedding and event cakes",
    services: ["Tiered cakes", "Fondant detailing", "Dessert tables", "Eggless options", "Cake table styling"],
    locations: ["Delhi", "Gurgaon", "Noida"],
    testimonials: [
      { author: "Sonal", text: "Looked premium and tasted far better than most event cakes." },
    ],
    reviewPrompt: "How were the cake design, taste, and delivery handling?",
  },
  {
    type: "Wedding DJ",
    subType: "Sangeet DJ",
    emoji: "🎧",
    city: "Noida",
    rating: 5,
    priceLevel: 3,
    budgetRange: { min: 50000, max: 180000 },
    typicalTiming: "4-6 hrs performance",
    serviceMode: "DJ and dance-floor energy",
    services: ["Sangeet DJ", "Cocktail set", "After-party playlist", "Sound rig", "Cold pyros sync"],
    locations: ["Noida", "Delhi", "Ghaziabad"],
    testimonials: [
      { author: "Armaan", text: "The DJ understood both family music and proper party energy." },
    ],
    reviewPrompt: "Review the song selection, transitions, and dance-floor energy.",
  },
  {
    type: "Pandit",
    subType: "Wedding Pandit",
    emoji: "🪔",
    city: "Delhi",
    rating: 5,
    priceLevel: 1,
    budgetRange: { min: 11000, max: 51000 },
    typicalTiming: "2-4 hrs rituals",
    serviceMode: "Wedding rituals and guidance",
    services: ["Phera rituals", "Muhurat planning", "Sankalp guidance", "Bilingual explanations", "Samagri checklist"],
    locations: ["Delhi", "Gurgaon", "Noida"],
    testimonials: [
      { author: "The Bhatias", text: "Calm, punctual, and explained each step clearly for both families." },
    ],
    reviewPrompt: "Share how clearly the rituals were explained and how smoothly the ceremony ran.",
  },
  {
    type: "Photobooth",
    subType: "Instant Print Booth",
    emoji: "📷",
    city: "Gurgaon",
    rating: 4,
    priceLevel: 2,
    budgetRange: { min: 20000, max: 90000 },
    typicalTiming: "Per function setup",
    serviceMode: "Photo booth and instant print setup",
    services: ["Photo booth backdrop", "Instant prints", "GIF booth", "Custom props", "Guest album station"],
    locations: ["Gurgaon", "Delhi", "Noida"],
    testimonials: [
      { author: "Ritika", text: "The booth kept guests busy and gave us a fun printed memory wall." },
    ],
    reviewPrompt: "How was the booth setup, queue management, and print quality?",
  },
  {
    type: "Astrologers",
    subType: "Muhurat Consultation",
    emoji: "🔮",
    city: "Varanasi",
    rating: 4,
    priceLevel: 1,
    budgetRange: { min: 5000, max: 35000 },
    typicalTiming: "By appointment",
    serviceMode: "Kundli and muhurat consultations",
    services: ["Kundli matching", "Muhurat selection", "Name compatibility", "Remedy guidance", "Family consultation calls"],
    locations: ["Varanasi", "Delhi", "Online nationwide"],
    testimonials: [
      { author: "Sneha", text: "Helpful for families who wanted a clear muhurat and guidance in one place." },
    ],
    reviewPrompt: "How clear and useful was the consultation?",
  },
  {
    type: "Party Places",
    subType: "Cocktail Venues",
    bundledServices: ["Catering", "Wedding DJ"],
    emoji: "🎉",
    city: "Delhi",
    rating: 4,
    priceLevel: 3,
    budgetRange: { min: 80000, max: 350000 },
    guestRange: { min: 50, max: 250 },
    typicalTiming: "Half-day to full-day booking",
    serviceMode: "Pre-wedding event spaces",
    services: ["Cocktail venues", "Intimate function spaces", "Rooftop party areas", "Private dining rooms", "Birthday and after-party bookings"],
    locations: ["Delhi", "Gurgaon", "Noida"],
    testimonials: [
      { author: "Nakul", text: "Perfect for the after-party and much easier than a full banquet booking." },
    ],
    reviewPrompt: "How was the space quality, atmosphere, and event support?",
  },
  {
    type: "Choreographer",
    subType: "Family Performances",
    emoji: "💃",
    city: "Gurgaon",
    rating: 5,
    priceLevel: 3,
    budgetRange: { min: 30000, max: 175000 },
    typicalTiming: "6-10 practice sessions",
    serviceMode: "Family dance direction",
    services: ["Sangeet concept planning", "Couple performance mix", "Family medleys", "At-home rehearsals", "Stage blocking support"],
    locations: ["Gurgaon", "Delhi", "Noida"],
    testimonials: [
      { author: "Kartik", text: "They made non-dancers feel comfortable and still delivered a sharp performance." },
    ],
    reviewPrompt: "Tell others how the sessions felt and whether the routines were wedding-friendly.",
  },
  {
    type: "Bride",
    subType: "Bridal Jewellery",
    emoji: "👰",
    city: "Delhi",
    rating: 5,
    priceLevel: 4,
    budgetRange: { min: 75000, max: 600000 },
    typicalTiming: "By appointment",
    serviceMode: "Bridal styling and jewellery",
    services: ["Polki sets", "Temple jewellery", "Styling consults", "Bridal trial styling", "Accessory pairing"],
    locations: ["Delhi", "Chandni Chowk", "Karol Bagh"],
    testimonials: [
      { author: "Pallavi", text: "They helped balance statement pieces without overloading the bridal look." },
    ],
    reviewPrompt: "How was the collection quality, styling guidance, and after-sales support?",
  },
  {
    type: "Groom",
    subType: "Sherwani",
    emoji: "🤵",
    city: "Delhi",
    rating: 4,
    priceLevel: 3,
    budgetRange: { min: 25000, max: 175000 },
    typicalTiming: "Appointment and fitting based",
    serviceMode: "Sherwani and groom styling",
    services: ["Sherwani trials", "Custom tailoring", "Safa pairing", "Mojari styling", "Last-mile alterations"],
    locations: ["Delhi", "Noida", "Jaipur"],
    testimonials: [
      { author: "Aditya", text: "The fit and styling support made the groom look put together without overdoing it." },
    ],
    reviewPrompt: "Review the fit, styling support, and tailoring quality.",
  },
];

export const DEFAULT_VENDORS = DEFAULT_VENDOR_CATALOG.map((vendor, index) => ({
  id: index + 1,
  name: `VivahGo's Choice ${vendor.type}`,
  booked: false,
  featured: true,
  featuredLabel: "VivahGo's Choice",
  reviewCount: vendor.testimonials.length + (vendor.rating >= 5 ? 18 : 11),
  ...vendor,
}));

export const DEFAULT_TASKS = [
  { id:1, name:"Finalize overall wedding calendar", done:true, due:"6 months before", priority:"high", group:"6 months", eventId:"", ceremony:"General" },
  { id:2, name:"Book main wedding venue", done:true, due:"6 months before", priority:"high", group:"6 months", eventId:9, ceremony:"Pheras" },
  { id:3, name:"Block guest room inventory", done:false, due:"5 months before", priority:"high", group:"5 months", eventId:"", ceremony:"General" },
  { id:4, name:"Freeze photography and video team", done:false, due:"5 months before", priority:"high", group:"5 months", eventId:"", ceremony:"General" },
  { id:5, name:"Finalize Roka guest flow", done:false, due:"4 months before", priority:"medium", group:"4 months", eventId:1, ceremony:"Roka" },
  { id:6, name:"Arrange Sagai ring and stage design", done:false, due:"4 months before", priority:"medium", group:"4 months", eventId:2, ceremony:"Sagai" },
  { id:7, name:"Book haldi floral decor", done:false, due:"3 months before", priority:"high", group:"3 months", eventId:4, ceremony:"Haldi" },
  { id:8, name:"Finalize mehndi artists", done:false, due:"3 months before", priority:"high", group:"3 months", eventId:5, ceremony:"Mehndi" },
  { id:9, name:"Freeze Sangeet choreography slots", done:false, due:"3 months before", priority:"medium", group:"3 months", eventId:6, ceremony:"Sangeet" },
  { id:10, name:"Send invitation cards and e-invites", done:false, due:"2 months before", priority:"high", group:"2 months", eventId:"", ceremony:"General" },
  { id:11, name:"Assign family welcome teams", done:false, due:"2 months before", priority:"medium", group:"2 months", eventId:"", ceremony:"General" },
  { id:12, name:"Finalize baraat transport logistics", done:false, due:"1 month before", priority:"high", group:"1 month", eventId:7, ceremony:"Baraat" },
  { id:13, name:"Confirm jaimala setup and sequence", done:false, due:"1 month before", priority:"medium", group:"1 month", eventId:8, ceremony:"Jaimala" },
  { id:14, name:"Confirm pandit and phera muhurat", done:false, due:"1 month before", priority:"high", group:"1 month", eventId:9, ceremony:"Pheras" },
  { id:15, name:"Prepare kanyadaan rituals checklist", done:false, due:"3 weeks before", priority:"medium", group:"Final", eventId:10, ceremony:"Kanyadaan" },
  { id:16, name:"Finalize saptapadi vow prompts", done:false, due:"3 weeks before", priority:"medium", group:"Final", eventId:11, ceremony:"Saptapadi" },
  { id:17, name:"Arrange sindoor daan items", done:false, due:"2 weeks before", priority:"high", group:"Final", eventId:12, ceremony:"Sindoor Daan" },
  { id:18, name:"Confirm reception stage and MC plan", done:false, due:"2 weeks before", priority:"high", group:"Final", eventId:13, ceremony:"Reception" },
  { id:19, name:"Finalize vidaai vehicle and timing", done:false, due:"1 week before", priority:"high", group:"Final", eventId:14, ceremony:"Vidaai" },
  { id:20, name:"Prepare griha pravesh welcome setup", done:false, due:"1 week before", priority:"medium", group:"Final", eventId:15, ceremony:"Griha Pravesh" },
  { id:21, name:"Print emergency vendor contact sheet", done:false, due:"5 days before", priority:"high", group:"Final", eventId:"", ceremony:"General" },
  { id:22, name:"Pack jewelry and attire day-wise", done:false, due:"4 days before", priority:"high", group:"Final", eventId:"", ceremony:"General" },
  { id:23, name:"Share final timeline with core family", done:false, due:"3 days before", priority:"high", group:"Final", eventId:"", ceremony:"General" },
  { id:24, name:"Settle pending vendor balances", done:false, due:"2 days before", priority:"high", group:"Final", eventId:"", ceremony:"General" },
  { id:25, name:"Create post-event photo backup plan", done:false, due:"After wedding", priority:"low", group:"Post Wedding", eventId:"", ceremony:"General" },
];

export const QUESTIONS = [
  { key:"bride", q:"What is the bride's name? 🌸", placeholder:"Enter bride's name...", type:"text" },
  { key:"groom", q:"And the groom's name? 🤵", placeholder:"Enter groom's name...", type:"text" },
  { key:"date", q:"What's your dream wedding date? 📅", placeholder:"e.g. 25 November 2025", type:"text" },
  { key:"venue", q:"Which city or venue are you considering? 🏛️", placeholder:"e.g. Delhi, Jaipur, Udaipur...", type:"text" },
  { key:"guests", q:"How many guests are you expecting? 👨‍👩‍👧‍👦", placeholder:"e.g. 300", type:"text" },
  { key:"budget", q:"What's your total wedding budget (₹)? 💰", placeholder:"e.g. 50,00,000", type:"text" },
];

export const AI_RESPONSES = [
  "Wonderful! ",
  "Lovely name! ",
  "Exciting! ",
  "Great choice! ",
  "Perfect! ",
  "Excellent! ",
];
