version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "npm"
    directory: "/vivahgo"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "@eslint/js"
      - dependency-name: "eslint-plugin-react-hooks"
      - dependency-name: "eslint-plugin-react-refresh"

  - package-ecosystem: "npm"
    directory: "/my-video"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
